# Generated by Django 5.1.4 on 2024-12-16 20:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                ("telefone", models.CharField(blank=True, max_length=20, null=True)),
                ("email", models.EmailField(max_length=254)),
                ("mensagem", models.TextField()),
                (
                    "data_recebimento",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("resposta", models.TextField(blank=True, null=True)),
                ("data_resposta", models.DateTimeField(blank=True, null=True)),
                ("respondido", models.BooleanField(default=False)),
            ],
        ),
    ]
