# Generated by Django 5.1 on 2024-11-25 17:14
from django.db import migrations, models
class Migration(migrations.Migration):
    dependencies = [
        ('subscriptions', '0001_initial'),
        ('subscriptions', '0002_alter_subscription_options_alter_subscription_cpf_and_more.py'),
        ('subscriptions', '0003_alter_subscription_options_subscription_paid_and_more.py'),
    ]
    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='paid',
            field=models.BooleanField(default=False, verbose_name='pago'),
        ),
    ]